services:
  - type: web
    name: ccmc-maternal-tracker
    env: docker
    region: singapore
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: EXCEL_URL
        value: https://docs.google.com/spreadsheets/d/1T1sthQZftwJEyve2wuyAwVZ55sr8TvgwhQJFEdEmAmA/export?format=xlsx
      - key: PYTHONUNBUFFERED
        value: "1"
